apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
         name: mongo
    spec:
      containers:
        - name: mongo-container
          imagePullPolicy: Always
          image: mongo:3.2
          ports:
            - name: http-port
              containerPort: 27017
          volumeMounts:
            - name: mongo
              mountPath: /data/db
      volumes:
        - name: mongo
          persistentVolumeClaim:
            claimName: mongo-data
