apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gep-poc-tha-container
spec:
  replicas: 1
  template:
    metadata:
      labels:
	app: gep-poc-tha-app
    spec:
      containers:
        - name: jenkins-container
          imagePullPolicy: Always
          image: tharanirajan/gep-poc-tha-jenkins:2.0
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
